plugins {
    id 'java'
    id 'application'
}

group 'dev.blackdev'
version '1.0-SNAPSHOT'

sourceCompatibility = '1.8'

mainClassName = 'dev.blackdev.Main'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
 implementation 'com.github.JnCrMx:discord-game-sdk4j:v1.0.0'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}